### ISSUE TITLE
.gif files can have video/mp4 mime type

### ISSUE THREAD

**Issue by sfan5** [sfan5/pytgbridge#3]
fuck telegram

<pre>
m.file_id = 'CgADAgADvgEAApFb-Um02_fq_Czq0QI'
m.file_name = 'video'
m.file_size = 1745632
m.mime_type = 'video/mp4'
m.thumb (PhotoSize)
m.thumb.file_id = 'AAQCABM63TgOAASkfcQdKP6jVISjAAIC'
m.thumb.file_size = 2457
m.thumb.height = 90
m.thumb.width = 63
</pre>

<pre>
Input #0, gif, from 'file_1.mp4':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: gif, bgra, 364x520, 12.50 fps, 12.50 tbr, 100 tbn, 100 tbc
</pre>

**Comment by RaymondSchnyder** [comment]
GIF Files are really small and short, maybe do a little "detection" if the video file could be a gif.
