### ISSUE TITLE
Add "mention translation"

### ISSUE THREAD

**Issue by cactushydrocodone** [sfan5/pytgbridge#5]
Some have different nicknames on different irc networks.
As i also have a different username / nickname on telegram, it would  be cool to replace "mentions" on IRC to the correct username on telegram

Example:

IRC network:
<hanspeter> hey EricTheCock!

Telegram:
\@BOT: <hanspeter> hey \@PussyDestroyer!

**Comment by sfan5** [comment]
Hmm, no.
