### ISSUE TITLE
ADDING NEW IRC EVENTS

### ISSUE THREAD

**Issue by radmx** [sfan5/pytgbridge#6]
how can i add more irc events to the conf.json file?? i mean, lot more that the conf already have

**Comment by sfan5** [comment]
What do you mean by "irc events"?

**Comment by radmx** [comment]
yeah , in your code is this under bridge options:

			"telegram_show_joins": true, // show joins/parts from IRC on Telegram

and i was wondering if can be added more IRC EVENTS like  part,  nick changes, quit, topic, notice, under the same format 			"telegram_show_<event>": true/false, // show <event> from IRC on Telegram

and if so, wich ones are avalible?

**Comment by sfan5** [comment]
Everything that is currently available is mentioned in the config.
