### ISSUE TITLE
How to convert sticker and animated sticker to emoji

### ISSUE THREAD

**Issue by dalfast** [sfan5/pytgbridge#8]
Hello,

How to convert sticker and animated sticker to emoji?
I just want convert sticker and animated sticker show just emoji on irc without link or web backend.
Thank you.

Regards.

**Comment by sfan5** [comment]
You can disable file downloading for stickers by editing the following code part:
https://github.com/sfan5/pytgbridge/blob/aab0081b7679d52497007c2a02ce6addd2ea79dd/src/bridge.py#L400-L410

Add this:
```python
		else:
			self.irc.privmsg(l.irc, self._tg_format_msg_prefix(event) + " " + mediadesc)
			return
```

**Comment by dalfast** [comment]
Thank you for fastest response.
Once again, I put this relay on irc channel with other relay bot or relay bridge ,
The bot mention or reply the bot relay nick not nick from relay
like : <relaybot> <nick> or <relaybot> nick
how to mention/reply <nick> or nick without mention/reply <relaybot> 
some other relaybot can quote and reply with their chat, offcourse he have cut some text messages, not quote all messages
This the best Telegram/IRC bridge I ever use, maybe some of improvement make the best.
